### ISSUE TITLE
[Documentation]: A4 Handout

### ISSUE THREAD

**Issue by FischkopDev** [FischkopDev/Game-development-AP-Uni-Heidelberg#1]
Write down everything as a handout for Prof. Hesser.

**Comment by Chris9667** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HandOut A4 for first review to Prof. Hesser](https://trello.com/c/fvVnB0Ch/7-handout-a4-for-first-review-to-prof-hesser)
