### ISSUE TITLE
[Documentation]: UC-Diagram

### ISSUE THREAD

**Issue by FischkopDev** [FischkopDev/Game-development-AP-Uni-Heidelberg#2]
Create Use case diagrams for all scenes

**Comment by Chris9667** [comment]
das wird krass

**Comment by Chris9667** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UML Use-case diagrams](https://trello.com/c/USB4rvoJ/5-uml-use-case-diagrams)
